                </td>
              </tr>
            </table>
          </div>
          <div class="inner_div"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--slider_preview-->
<div id="slider_preview" class="choose_ad_formats"
     style="background: none; float: none;  height: 1px; box-shadow: none">
  <div class="tips"
       style="position: fixed;z-index: 1000000; display: none; width: 350px; padding-bottom: 0;">
    <div align="right" style="height: 14px;">
      <span class="cl"></span>
    </div>
    <a href="http://facebook.com" target="_blank" class="clickurl">
      <span class="title">Facebook Advertising</span>
                                        <span class="desc">Reach The Exact Audience You Want<br>
                                        With Relevant Targeted Ads.</span>
      <span class="url">www.facebook.com</span>
    </a>
    <div align="right" class="ads_by_yepty"><a href="http://yepty.com" target="_blank"
      ><span>Yepty.com</span></a>Ads by&nbsp;</div>
  </div>
</div>
<!--end slider_preview-->
<!--adline_preview-->
<div id="adline_preview" class="choose_ad_formats"
     style="background: none; float: none;  height: 1px; box-shadow: none; ">
  <div class="tips"
       style="position: fixed; display: none; top: 0px; left: 0px; width: 100%;z-index: 100000; padding: 0; box-shadow: none; height: 36px; background: #f5f5f5; border: 1px solid #E5E5E5;">

    <div style="float: right;"><span class="cl"></span></div>

    <table cellspacing="0" onclick="window.open('http://facebook.com')">
      <tr>
        <td>
          <div class="ads_by_yepty"
               style="min-width: 115px; top: 0px; min-height: 22px; font-size: 12px;line-height: 26px; padding: 5px 0 0 10px !important">
            <a href="http://yepty.com" target="_blank"
               style="background-position: 0px 5px"><span>Yepty.com</span></a>Ads by&nbsp;</div>
        </td>
        <td><span class="title" style="font-weight: bold; margin-top: 0; line-height: 26px;">Facebook Advertising | Facebook.com</span>
        </td>
        <td><span class="price small_price">$1449.99</span></td>
        <td><span class="desc">Reach The Exact Audience You Want With Relevant Targeted Ads.</span></td>
      </tr>
    </table>

  </div>
</div>
<!--end adline_preview-->

<script type="text/javascript" src="http://heartcode-canvasloader.googlecode.com/files/heartcode-canvasloader-min-0.9.js"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/nicecheckbox.js'; ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/niceradio.js' ?>"></script>

<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/jquery.tools.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/farbtastic/farbtastic.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/jquery.ui-slider.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/jquery-ui.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/tipsy/jquery.tipsy.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/constructor.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/formData.js' ?>"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL . '/yepty/js/cusel.js' ?>"></script>



<input type="hidden" id="yeptyImgPath" value="<?php echo $imgPath; ?>">


