<!--yepty_promo-->
<table cellspacing="5" border="0" class="yepty_promo">
  <tr>
    <td>
      <div class="yepty_facebook_like bt" style="overflow: visible">
        <div class="yepty_promo_text">Do you like this plugin?</div>
        <table cellspacing="0" border="0">
          <tr>
            <td align="left">
              <?php echo "<img src='" . $imgPath . "facebook.png'>";?>
            </td>
            <td align="center">
              <a href="javascript: var uri = encodeURIComponent('http://wordpress.org/extend/plugins/yepty/'); var title=encodeURIComponent('Yepty - Pay Per Click Advertising. SkyRocket Your Income with In-text, In-image and Slider Ads.'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                <?php echo "<img src='" . $imgPath . "like.png'>";?>
              </a>
            </td>
          </tr>
        </table>
      </div>
    </td>
    <td>
      <div class="yepty_twitter_like bt">
        <div class="yepty_promo_text">Tweet about Plugin</div>
        <div style="padding-left: 38px; width: 40px;">
          <a href="javascript: var uri = encodeURIComponent('http://wordpress.org/extend/plugins/yepty/'); var title=encodeURIComponent('Yepty - Pay Per Click Advertising. SkyRocket Your Income with In-text, In-image and Slider Ads.'); window.open('http://twitter.com/share?url='+uri+'&text='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
            <?php echo "<img src='" . $imgPath . "tweet.png'>";?>
          </a>
        </div>
      </div>
    </td>
    <td>
      <div class="yepty_fan bt" style="width: 125px; overflow: visible">

        <div class="yepty_promo_text">Recommend plugin</div>
        <div style="padding: 2px 0 0 35px; width: 50px;">
          <a href="javascript: var uri = encodeURIComponent('http://wordpress.org/extend/plugins/yepty/'); window.open('https://plusone.google.com/_/+1/confirm?hl=en&url='+uri ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
            <?php echo "<img src='" . $imgPath . "google_plus.png'>";?>
          </a>
        </div>
      </div>
    </td>
    <td>
      <div class="yepty_fan bt" style="width: 205px; overflow: visible">
        <div class="yepty_promo_text">Become a Yepty Fan</div>
        <table style='margin-left: 9px' cellspacing="2" cellpadding="0" border="0">
          <tr>
            <td valign="top">
              <a href="https://twitter.com/#!/yepty_com" class="twitter-follow-button" data-show-count="false" data-lang="en">
                Follow
              </a>
              <script type="text/javascript"><!--
                (function(d, s, id) {
                  var js,fjs = d.getElementsByTagName(s)[0];
                  if (!d.getElementById(id)) {
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore(js, fjs);
                  }
                })(document, "script", "twitter-wjs");
              //--></script>
            </td>
            <td valign="top" style="padding-top: 1px;">
              <a href="javascript: var uri = encodeURIComponent('http://yepty.com/'); var title=encodeURIComponent('Yepty - Pay Per Click Advertising. SkyRocket Your Income with In-text, In-image and Slider Ads.'); window.open('http://www.facebook.com/sharer.php?u='+uri+'&t='+title ,null, 'toolbar=0, location=0, directories=0, status=0, menubar=0, scrollbars=0, resizable=0, width=850, height=750');void(0);">
                <?php echo "<img src='" . $imgPath . "like.png'>";?>
              </a>
            </td>
          </tr>
        </table>
      </div>
    </td>
    <td>
      <div class="yepty_rating bt">
        <div class="yepty_promo_text"> Give Us a</div>
        <a target="_blank" class="rating" href="http://wordpress.org/extend/plugins/yepty/" class="rating">perfect
          rating</a>

      </div>
    </td>
    <td>
      <!---- Ask a question, leave feedback or share your ideasg-->
      <div class="yepty_feedback bt">
        <a target="_blank" class="yepty_promo_text" href="http://community.yepty.com">Ask a question, leave
          feedback
          or share your ideas</a>

      </div>
      <!---end -Ask a question, leave feedback or share your ideas-->
    </td>
  </tr>
</table>
<!--endyepty_promo-->